"""Initial schema

Revision ID: 059ef1720c55
Revises: 
Create Date: 2026-08-30 07:44:15.356356
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '059ef1720c55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sa.Enum('LOCAL', 'GOOGLE', name='auth_provider'), nullable=False),
    sa.Column('google_sub', sa.String(length=256), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('email_analyses',
    sa.Column('analyst_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('sender_email', sa.String(length=320), nullable=True),
    sa.Column('sender_display_name', sa.String(length=256), nullable=True),
    sa.Column('sender_domain', sa.String(length=253), nullable=True),
    sa.Column('reply_to', sa.Text(), nullable=True),
    sa.Column('recipients', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_id', sa.String(length=512), nullable=True),
    sa.Column('email_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_eml_gcs_path', sa.Text(), nullable=True),
    sa.Column('raw_eml_sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_eml_size_bytes', sa.Integer(), nullable=True),
    sa.Column('received_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('all_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authentication_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spf_result', sa.String(length=32), nullable=True),
    sa.Column('dkim_result', sa.String(length=32), nullable=True),
    sa.Column('dmarc_result', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETE', 'FAILED', 'QUARANTINED', name='analysis_status'), nullable=False),
    sa.Column('threat_category', sa.Enum('PHISHING', 'SPEAR_PHISHING', 'BEC', 'MALWARE', 'SPAM', 'RANSOMWARE', 'CREDENTIAL_HARVEST', 'SOCIAL_ENGINEERING', 'UNKNOWN', 'BENIGN', name='threat_category'), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO', name='severity_level'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('threat_score', sa.Float(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_reasoning', sa.Text(), nullable=True),
    sa.Column('ai_indicators', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model_used', sa.String(length=128), nullable=True),
    sa.Column('enrichment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geo_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_gcs_path', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_email_analyses_analyst_id'), 'email_analyses', ['analyst_id'], unique=False)
    op.create_index(op.f('ix_email_analyses_campaign_id'), 'email_analyses', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_email_analyses_sender_domain'), 'email_analyses', ['sender_domain'], unique=False)
    op.create_index(op.f('ix_email_analyses_sender_email'), 'email_analyses', ['sender_email'], unique=False)
    op.create_index(op.f('ix_email_analyses_severity'), 'email_analyses', ['severity'], unique=False)
    op.create_index(op.f('ix_email_analyses_status'), 'email_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_email_analyses_threat_category'), 'email_analyses', ['threat_category'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False, comment='Groups tokens in a rotation chain. Revoke entire family on reuse.'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('email_attachments',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('md5_hash', sa.String(length=32), nullable=True),
    sa.Column('gcs_path', sa.Text(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('vt_scan_id', sa.String(length=256), nullable=True),
    sa.Column('vt_detections', sa.Integer(), nullable=True),
    sa.Column('vt_total_engines', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachments_analysis_id'), 'email_attachments', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_email_attachments_sha256_hash'), 'email_attachments', ['sha256_hash'], unique=False)
    op.create_table('iocs',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('ioc_type', sa.Enum('IP_ADDRESS', 'DOMAIN', 'URL', 'EMAIL', 'FILE_HASH_MD5', 'FILE_HASH_SHA256', 'FILE_HASH_SHA1', 'HEADER', 'USER_AGENT', 'BITCOIN_ADDRESS', 'CVE', 'OTHER', name='ioc_type'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_malicious', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enrichment_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iocs_analysis_id'), 'iocs', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    op.create_table('threat_records',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('VIRUSTOTAL', 'ABUSEIPDB', 'SHODAN', 'INTERNAL', 'MCP_TOOL', 'AI_CLASSIFIER', name='threat_provider'), nullable=False),
    sa.Column('indicator', sa.Text(), nullable=False),
    sa.Column('indicator_type', sa.String(length=64), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=True),
    sa.Column('malicious_count', sa.Integer(), nullable=True),
    sa.Column('total_engines', sa.Integer(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('asn', sa.String(length=32), nullable=True),
    sa.Column('isp', sa.String(length=256), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lon', sa.Float(), nullable=True),
    sa.Column('geo_city', sa.String(length=128), nullable=True),
    sa.Column('geo_region', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['email_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_records_analysis_id'), 'threat_records', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_threat_records_indicator'), 'threat_records', ['indicator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_records_indicator'), table_name='threat_records')
    op.drop_index(op.f('ix_threat_records_analysis_id'), table_name='threat_records')
    op.drop_table('threat_records')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_analysis_id'), table_name='iocs')
    op.drop_table('iocs')
    op.drop_index(op.f('ix_email_attachments_sha256_hash'), table_name='email_attachments')
    op.drop_index(op.f('ix_email_attachments_analysis_id'), table_name='email_attachments')
    op.drop_table('email_attachments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_email_analyses_threat_category'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_status'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_severity'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_sender_email'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_sender_domain'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_campaign_id'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_analyst_id'), table_name='email_analyses')
    op.drop_table('email_analyses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
