"""gmail_integration

Revision ID: 539c7007dbf1
Revises: ed01581368ef
Create Date: 2026-08-30 10:25:05.989773
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '539c7007dbf1'
down_revision: Union[str, None] = 'ed01581368ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_sync_jobs',
    sa.Column('job_id', sa.String(length=128), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('gmail_connection_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED', name='sync_job_status'), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gmail_connection_id'], ['gmail_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_gmail_sync_jobs_gmail_connection_id'), 'gmail_sync_jobs', ['gmail_connection_id'], unique=False)
    op.create_index(op.f('ix_gmail_sync_jobs_status'), 'gmail_sync_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_gmail_sync_jobs_workspace_id'), 'gmail_sync_jobs', ['workspace_id'], unique=False)
    op.add_column('email_analyses', sa.Column('source_provider', sa.String(length=64), nullable=True))
    op.add_column('email_analyses', sa.Column('source_message_id', sa.String(length=256), nullable=True))
    op.drop_constraint(op.f('email_analyses_message_id_key'), 'email_analyses', type_='unique')
    op.create_index(op.f('ix_email_analyses_message_id'), 'email_analyses', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_analyses_source_message_id'), 'email_analyses', ['source_message_id'], unique=False)
    op.create_index(op.f('ix_email_analyses_source_provider'), 'email_analyses', ['source_provider'], unique=False)
    op.create_unique_constraint('uq_workspace_source_msg', 'email_analyses', ['workspace_id', 'source_provider', 'source_message_id'])
    op.add_column('gmail_connections', sa.Column('provider', sa.String(length=64), nullable=False))
    op.add_column('gmail_connections', sa.Column('encrypted_access_token', sa.Text(), nullable=True))
    op.add_column('gmail_connections', sa.Column('encrypted_refresh_token', sa.Text(), nullable=True))
    op.add_column('gmail_connections', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('gmail_connections', sa.Column('scopes', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('gmail_connections', sa.Column('status', sa.String(length=64), nullable=False))
    op.add_column('gmail_connections', sa.Column('last_sync_cursor', sa.String(length=256), nullable=True))
    op.add_column('gmail_connections', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('gmail_connections', 'credentials_json')
    op.drop_column('gmail_connections', 'sync_status')
    op.drop_column('gmail_connections', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gmail_connections', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('gmail_connections', sa.Column('sync_status', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('gmail_connections', sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('gmail_connections', 'revoked_at')
    op.drop_column('gmail_connections', 'last_sync_cursor')
    op.drop_column('gmail_connections', 'status')
    op.drop_column('gmail_connections', 'scopes')
    op.drop_column('gmail_connections', 'token_expires_at')
    op.drop_column('gmail_connections', 'encrypted_refresh_token')
    op.drop_column('gmail_connections', 'encrypted_access_token')
    op.drop_column('gmail_connections', 'provider')
    op.drop_constraint('uq_workspace_source_msg', 'email_analyses', type_='unique')
    op.drop_index(op.f('ix_email_analyses_source_provider'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_source_message_id'), table_name='email_analyses')
    op.drop_index(op.f('ix_email_analyses_message_id'), table_name='email_analyses')
    op.create_unique_constraint(op.f('email_analyses_message_id_key'), 'email_analyses', ['message_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('email_analyses', 'source_message_id')
    op.drop_column('email_analyses', 'source_provider')
    op.drop_index(op.f('ix_gmail_sync_jobs_workspace_id'), table_name='gmail_sync_jobs')
    op.drop_index(op.f('ix_gmail_sync_jobs_status'), table_name='gmail_sync_jobs')
    op.drop_index(op.f('ix_gmail_sync_jobs_gmail_connection_id'), table_name='gmail_sync_jobs')
    op.drop_table('gmail_sync_jobs')
    # ### end Alembic commands ###
