"""workspace_isolation

Revision ID: c2bcad20a5dd
Revises: 7d3eb1716d65
Create Date: 2026-08-30 09:29:19.981747
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c2bcad20a5dd'
down_revision: Union[str, None] = '7d3eb1716d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_connections',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('credentials_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gmail_connections_user_id'), 'gmail_connections', ['user_id'], unique=False)
    op.create_index(op.f('ix_gmail_connections_workspace_id'), 'gmail_connections', ['workspace_id'], unique=False)
    op.add_column('email_analyses', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_email_analyses_workspace_id'), 'email_analyses', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'email_analyses', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('email_attachments', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_email_attachments_workspace_id'), 'email_attachments', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'email_attachments', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('iocs', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_iocs_workspace_id'), 'iocs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'iocs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('threat_records', sa.Column('workspace_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_threat_records_workspace_id'), 'threat_records', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'threat_records', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'threat_records', type_='foreignkey')
    op.drop_index(op.f('ix_threat_records_workspace_id'), table_name='threat_records')
    op.drop_column('threat_records', 'workspace_id')
    op.drop_constraint(None, 'iocs', type_='foreignkey')
    op.drop_index(op.f('ix_iocs_workspace_id'), table_name='iocs')
    op.drop_column('iocs', 'workspace_id')
    op.drop_constraint(None, 'email_attachments', type_='foreignkey')
    op.drop_index(op.f('ix_email_attachments_workspace_id'), table_name='email_attachments')
    op.drop_column('email_attachments', 'workspace_id')
    op.drop_constraint(None, 'email_analyses', type_='foreignkey')
    op.drop_index(op.f('ix_email_analyses_workspace_id'), table_name='email_analyses')
    op.drop_column('email_analyses', 'workspace_id')
    op.drop_index(op.f('ix_gmail_connections_workspace_id'), table_name='gmail_connections')
    op.drop_index(op.f('ix_gmail_connections_user_id'), table_name='gmail_connections')
    op.drop_table('gmail_connections')
    # ### end Alembic commands ###
